@baseUrl = http://localhost:3000/api

###
POST {{baseUrl}}/hello
Content-Type: application/json

{
    "name": "Tentenko"
}

###
GET {{baseUrl}}/hello

###
GET {{baseUrl}}/session
cookie: {{cookie}}

###
GET {{baseUrl}}/wall
cookie: {{cookie}}

### 
GET {{baseUrl}}/proxy/catch-all

###
GET {{baseUrl}}/proxy/isolate/endpoint
