#!/bin/sh
# This file is autogenerated - DO NOT EDIT!
set -euo pipefail
BASE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="${BASE_DIR}/.."
(
cd ${REPO_DIR}
kubectl create namespace openfga --dry-run=client -o yaml | kubectl apply -f -
helm repo add openfga https://openfga.github.io/helm-charts
helm upgrade --install openfga openfga/openfga -f openfga/values.yaml -n openfga
)
